// Code generated by MockGen. DO NOT EDIT.
// Source: kv_file.go
//
// Generated by this command:
//
//	mockgen -source kv_file.go -destination kv_file_mocks.go -package common
//

// Package common is a generated GoMock package.
package common

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockKVFile is a mock of KVFile interface.
type MockKVFile[K comparable, V any] struct {
	ctrl     *gomock.Controller
	recorder *MockKVFileMockRecorder[K, V]
	isgomock struct{}
}

// MockKVFileMockRecorder is the mock recorder for MockKVFile.
type MockKVFileMockRecorder[K comparable, V any] struct {
	mock *MockKVFile[K, V]
}

// NewMockKVFile creates a new mock instance.
func NewMockKVFile[K comparable, V any](ctrl *gomock.Controller) *MockKVFile[K, V] {
	mock := &MockKVFile[K, V]{ctrl: ctrl}
	mock.recorder = &MockKVFileMockRecorder[K, V]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKVFile[K, V]) EXPECT() *MockKVFileMockRecorder[K, V] {
	return m.recorder
}

// Close mocks base method.
func (m *MockKVFile[K, V]) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockKVFileMockRecorder[K, V]) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockKVFile[K, V])(nil).Close))
}

// FileSize mocks base method.
func (m *MockKVFile[K, V]) FileSize() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileSize")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// FileSize indicates an expected call of FileSize.
func (mr *MockKVFileMockRecorder[K, V]) FileSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileSize", reflect.TypeOf((*MockKVFile[K, V])(nil).FileSize))
}

// Flush mocks base method.
func (m *MockKVFile[K, V]) Flush() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush")
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockKVFileMockRecorder[K, V]) Flush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockKVFile[K, V])(nil).Flush))
}

// Get mocks base method.
func (m *MockKVFile[K, V]) Get(key K) (*V, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(*V)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockKVFileMockRecorder[K, V]) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockKVFile[K, V])(nil).Get), key)
}

// GetAll mocks base method.
func (m *MockKVFile[K, V]) GetAll() (map[K]V, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].(map[K]V)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockKVFileMockRecorder[K, V]) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockKVFile[K, V])(nil).GetAll))
}

// Set mocks base method.
func (m *MockKVFile[K, V]) Set(key K, value V) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockKVFileMockRecorder[K, V]) Set(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockKVFile[K, V])(nil).Set), key, value)
}

// SetBatch mocks base method.
func (m *MockKVFile[K, V]) SetBatch(entries map[K]V) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBatch", entries)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBatch indicates an expected call of SetBatch.
func (mr *MockKVFileMockRecorder[K, V]) SetBatch(entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBatch", reflect.TypeOf((*MockKVFile[K, V])(nil).SetBatch), entries)
}

// Size mocks base method.
func (m *MockKVFile[K, V]) Size() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Size")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// Size indicates an expected call of Size.
func (mr *MockKVFileMockRecorder[K, V]) Size() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Size", reflect.TypeOf((*MockKVFile[K, V])(nil).Size))
}

// MockKVFileWithMemoryFootprint is a mock of KVFileWithMemoryFootprint interface.
type MockKVFileWithMemoryFootprint[K comparable, V any] struct {
	ctrl     *gomock.Controller
	recorder *MockKVFileWithMemoryFootprintMockRecorder[K, V]
	isgomock struct{}
}

// MockKVFileWithMemoryFootprintMockRecorder is the mock recorder for MockKVFileWithMemoryFootprint.
type MockKVFileWithMemoryFootprintMockRecorder[K comparable, V any] struct {
	mock *MockKVFileWithMemoryFootprint[K, V]
}

// NewMockKVFileWithMemoryFootprint creates a new mock instance.
func NewMockKVFileWithMemoryFootprint[K comparable, V any](ctrl *gomock.Controller) *MockKVFileWithMemoryFootprint[K, V] {
	mock := &MockKVFileWithMemoryFootprint[K, V]{ctrl: ctrl}
	mock.recorder = &MockKVFileWithMemoryFootprintMockRecorder[K, V]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKVFileWithMemoryFootprint[K, V]) EXPECT() *MockKVFileWithMemoryFootprintMockRecorder[K, V] {
	return m.recorder
}

// Close mocks base method.
func (m *MockKVFileWithMemoryFootprint[K, V]) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockKVFileWithMemoryFootprintMockRecorder[K, V]) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockKVFileWithMemoryFootprint[K, V])(nil).Close))
}

// FileSize mocks base method.
func (m *MockKVFileWithMemoryFootprint[K, V]) FileSize() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileSize")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// FileSize indicates an expected call of FileSize.
func (mr *MockKVFileWithMemoryFootprintMockRecorder[K, V]) FileSize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileSize", reflect.TypeOf((*MockKVFileWithMemoryFootprint[K, V])(nil).FileSize))
}

// Flush mocks base method.
func (m *MockKVFileWithMemoryFootprint[K, V]) Flush() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush")
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockKVFileWithMemoryFootprintMockRecorder[K, V]) Flush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockKVFileWithMemoryFootprint[K, V])(nil).Flush))
}

// Get mocks base method.
func (m *MockKVFileWithMemoryFootprint[K, V]) Get(key K) (*V, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(*V)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockKVFileWithMemoryFootprintMockRecorder[K, V]) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockKVFileWithMemoryFootprint[K, V])(nil).Get), key)
}

// GetAll mocks base method.
func (m *MockKVFileWithMemoryFootprint[K, V]) GetAll() (map[K]V, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].(map[K]V)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockKVFileWithMemoryFootprintMockRecorder[K, V]) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockKVFileWithMemoryFootprint[K, V])(nil).GetAll))
}

// GetMemoryFootprint mocks base method.
func (m *MockKVFileWithMemoryFootprint[K, V]) GetMemoryFootprint() *MemoryFootprint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMemoryFootprint")
	ret0, _ := ret[0].(*MemoryFootprint)
	return ret0
}

// GetMemoryFootprint indicates an expected call of GetMemoryFootprint.
func (mr *MockKVFileWithMemoryFootprintMockRecorder[K, V]) GetMemoryFootprint() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMemoryFootprint", reflect.TypeOf((*MockKVFileWithMemoryFootprint[K, V])(nil).GetMemoryFootprint))
}

// Set mocks base method.
func (m *MockKVFileWithMemoryFootprint[K, V]) Set(key K, value V) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockKVFileWithMemoryFootprintMockRecorder[K, V]) Set(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockKVFileWithMemoryFootprint[K, V])(nil).Set), key, value)
}

// SetBatch mocks base method.
func (m *MockKVFileWithMemoryFootprint[K, V]) SetBatch(entries map[K]V) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBatch", entries)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBatch indicates an expected call of SetBatch.
func (mr *MockKVFileWithMemoryFootprintMockRecorder[K, V]) SetBatch(entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBatch", reflect.TypeOf((*MockKVFileWithMemoryFootprint[K, V])(nil).SetBatch), entries)
}

// Size mocks base method.
func (m *MockKVFileWithMemoryFootprint[K, V]) Size() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Size")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// Size indicates an expected call of Size.
func (mr *MockKVFileWithMemoryFootprintMockRecorder[K, V]) Size() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Size", reflect.TypeOf((*MockKVFileWithMemoryFootprint[K, V])(nil).Size))
}
