// Copyright (c) 2025 Sonic Operations Ltd
//
// Use of this software is governed by the Business Source License included
// in the LICENSE file and at soniclabs.com/bsl11.
//
// Change Date: 2028-4-16
//
// On the date above, in accordance with the Business Source License, use of
// this software will be governed by the GNU Lesser General Public License v3.

package iter_utils

import "iter"

// Map2 maps an `iter.Seq2` of key-value pairs to another `iter.Seq2`
// of key-value pairs using the provided mapping function.
func Map2[KIn, VIn, KOut, VOut any](
	seq iter.Seq2[KIn, VIn],
	f func(KIn, VIn) (KOut, VOut),
) iter.Seq2[KOut, VOut] {
	return func(yield func(KOut, VOut) bool) {
		for k, v := range seq {
			if !yield(f(k, v)) {
				return
			}
		}
	}
}

// FromSliceWith creates an `iter.Seq2` from a slice of values,
// where the keys are generated by the provided key function.
func FromSliceWith[K comparable, V any](slice []V, keyFunc func(V) K) iter.Seq2[K, V] {
	return func(yield func(K, V) bool) {
		for _, v := range slice {
			if !yield(keyFunc(v), v) {
				return
			}
		}
	}
}
